---
image: "node:lts-alpine"

before_script:
- apk add make

pages:
  stage: deploy
  script:
    - npm i --no-audit
    - make out=public
  artifacts:
    paths:
      - public
  only:
    - master
---
